const provinces = [
    { Id: 79, Name: "Thành phố Hồ Chí Minh", Value: 79 },
    { Id: 1, Name: "Thành phố Hà Nội", Value: 1 },
    { Id: 31, Name: "Thành phố Hải Phòng", Value: 31 },
    { Id: 48, Name: "Thành phố Đà Nẵng", Value: 48 },
    { Id: 92, Name: "Thành phố Cần Thơ", Value: 92 },
    { Id: 2, Name: "Tỉnh Hà Giang", Value: 2 },
    { Id: 4, Name: "Tỉnh Cao Bằng", Value: 4 },
    { Id: 6, Name: "Tỉnh Bắc Kạn", Value: 6 },
    { Id: 8, Name: "Tỉnh Tuyên Quang", Value: 8 },
    { Id: 10, Name: "Tỉnh Lào Cai", Value: 10 },
    { Id: 11, Name: "Tỉnh Điện Biên", Value: 11 },
    { Id: 12, Name: "Tỉnh Lai Châu", Value: 12 },
    { Id: 14, Name: "Tỉnh Sơn La", Value: 14 },
    { Id: 15, Name: "Tỉnh Yên Bái", Value: 15 },
    { Id: 17, Name: "Tỉnh Hoà Bình", Value: 17 },
    { Id: 19, Name: "Tỉnh Thái Nguyên", Value: 19 },
    { Id: 20, Name: "Tỉnh Lạng Sơn", Value: 20 },
    { Id: 22, Name: "Tỉnh Quảng Ninh", Value: 22 },
    { Id: 24, Name: "Tỉnh Bắc Giang", Value: 24 },
    { Id: 25, Name: "Tỉnh Phú Thọ", Value: 25 },
    { Id: 26, Name: "Tỉnh Vĩnh Phúc", Value: 26 },
    { Id: 27, Name: "Tỉnh Bắc Ninh", Value: 27 },
    { Id: 30, Name: "Tỉnh Hải Dương", Value: 30 },
    { Id: 33, Name: "Tỉnh Hưng Yên", Value: 33 },
    { Id: 34, Name: "Tỉnh Thái Bình", Value: 34 },
    { Id: 35, Name: "Tỉnh Hà Nam", Value: 35 },
    { Id: 36, Name: "Tỉnh Nam Định", Value: 36 },
    { Id: 37, Name: "Tỉnh Ninh Bình", Value: 37 },
    { Id: 38, Name: "Tỉnh Thanh Hóa", Value: 38 },
    { Id: 40, Name: "Tỉnh Nghệ An", Value: 40 },
    { Id: 42, Name: "Tỉnh Hà Tĩnh", Value: 42 },
    { Id: 44, Name: "Tỉnh Quảng Bình", Value: 44 },
    { Id: 45, Name: "Tỉnh Quảng Trị", Value: 45 },
    { Id: 46, Name: "Tỉnh Thừa Thiên Huế", Value: 46 },
    { Id: 49, Name: "Tỉnh Quảng Nam", Value: 49 },
    { Id: 51, Name: "Tỉnh Quảng Ngãi", Value: 51 },
    { Id: 52, Name: "Tỉnh Bình Định", Value: 52 },
    { Id: 54, Name: "Tỉnh Phú Yên", Value: 54 },
    { Id: 56, Name: "Tỉnh Khánh Hòa", Value: 56 },
    { Id: 58, Name: "Tỉnh Ninh Thuận", Value: 58 },
    { Id: 60, Name: "Tỉnh Bình Thuận", Value: 60 },
    { Id: 62, Name: "Tỉnh Kon Tum", Value: 62 },
    { Id: 64, Name: "Tỉnh Gia Lai", Value: 64 },
    { Id: 66, Name: "Tỉnh Đắk Lắk", Value: 66 },
    { Id: 67, Name: "Tỉnh Đắk Nông", Value: 67 },
    { Id: 68, Name: "Tỉnh Lâm Đồng", Value: 68 },
    { Id: 70, Name: "Tỉnh Bình Phước", Value: 70 },
    { Id: 72, Name: "Tỉnh Tây Ninh", Value: 72 },
    { Id: 74, Name: "Tỉnh Bình Dương", Value: 74 },
    { Id: 75, Name: "Tỉnh Đồng Nai", Value: 75 },
    { Id: 77, Name: "Tỉnh Bà Rịa - Vũng Tàu", Value: 77 },
    { Id: 80, Name: "Tỉnh Long An", Value: 80 },
    { Id: 82, Name: "Tỉnh Tiền Giang", Value: 82 },
    { Id: 83, Name: "Tỉnh Bến Tre", Value: 83 },
    { Id: 84, Name: "Tỉnh Trà Vinh", Value: 84 },
    { Id: 86, Name: "Tỉnh Vĩnh Long", Value: 86 },
    { Id: 87, Name: "Tỉnh Đồng Tháp", Value: 87 },
    { Id: 89, Name: "Tỉnh An Giang", Value: 89 },
    { Id: 91, Name: "Tỉnh Kiên Giang", Value: 91 },
    { Id: 93, Name: "Tỉnh Hậu Giang", Value: 93 },
    { Id: 94, Name: "Tỉnh Sóc Trăng", Value: 94 },
    { Id: 95, Name: "Tỉnh Bạc Liêu", Value: 95 },
    { Id: 96, Name: "Tỉnh Cà Mau", Value: 96 }
]
export default provinces;